In [13]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib.dates as mdates
import matplotlib

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [14]:
#한글 깨짐 해결 방법
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import matplotlib.pyplot as plt

plt.rc('font', family='NanumBarunGothic')
plt.rcParams['axes.unicode_minus'] =False

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fonts-nanum is already the newest version (20200506-1).
0 upgraded, 0 newly installed, 0 to remove and 30 not upgraded.
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 12 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/humor-sans: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/usr/share/fonts/truetype/nanum: skipping, looped directory detected
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded

In [45]:
#KOSIS 데이터
fd_d = pd.read_csv('/content/drive/MyDrive/Data/미세먼지_Kosis.csv' , encoding='cp949') #미세먼지 데이터
ozon = pd.read_csv('/content/drive/MyDrive/Data/오존(10월)포함.csv' , encoding='cp949')

In [17]:
fd_d.head

<bound method NDFrame.head of     구분   항목  단위  2013.01 월  2013.04 월  2013.05 월  2013.06 월  2013.07 월  \
0   총계  월평균 NaN       64.0       54.0       60.0       46.0       38.0
1   서울  월평균 NaN       64.0       52.0       55.0       40.0       34.0
2   부산  월평균 NaN       56.0       49.0       62.0       47.0       47.0
3   대구  월평균 NaN       65.0       45.0       52.0       44.0       32.0
4   인천  월평균 NaN       63.0       59.0       60.0       48.0       39.0
5   광주  월평균 NaN       52.0       46.0       57.0       42.0       33.0
6   대전  월평균 NaN       58.0       48.0       53.0       40.0       28.0
7   울산  월평균 NaN       54.0       46.0       59.0       49.0       44.0
8   세종  월평균 NaN        NaN        NaN        NaN        NaN        NaN
9   경기  월평균 NaN       72.0       63.0       66.0       52.0       42.0
10  강원  월평균 NaN       72.0       57.0       60.0       41.0       36.0
11  충북  월평균 NaN       85.0       65.0       67.0       47.0       33.0
12  충남  월평균 NaN       53.0       51.0       55.0       39.0       30.0
13  전북  월평균 NaN       72.0       59.0       62.0       50.0       33.0
14  전남  월평균 NaN       48.0       40.0       52.0       35.0       34.0
15  경북  월평균 NaN       66.0       52.0       61.0       47.0       39.0
16  경남  월평균 NaN       61.0       47.0       58.0       44.0       37.0
17  제주  월평균 NaN       42.0       42.0       53.0       33.0       28.0

    2013.08 월  2013.09 월  ...  2022.03 월  2022.04 월  2022.05 월  2022.06 월  \
0        40.0       33.0  ...         42         39         33         22
1        35.0       28.0  ...         41         45         33         22
2        47.0       33.0  ...         38         32         31         19
3        39.0       31.0  ...         42         36         33         22
4        40.0       35.0  ...         42         44         32         21
5        32.0       33.0  ...         38         34         29         20
6        28.0       29.0  ...         44         39         31         21
7        49.0       32.0  ...         39         34         34         21
8         NaN        NaN  ...         46         40         31         22
9        44.0       37.0  ...         46         47         35         23
10       39.0       31.0  ...         37         36         29         20
11       36.0       34.0  ...         46         40         34         23
12       33.0       31.0  ...         46         44         34         22
13       33.0       38.0  ...         43         41         34         23
14       34.0       29.0  ...         35         31         29         20
15       42.0       35.0  ...         43         36         33         23
16       44.0       34.0  ...         34         29         29         19
17       32.0       33.0  ...         40         31         29         21

    2022.07 월  2022.08 월  2022.09 월  2022.10 월  2022.11 월  2022.12 월
0          22         19         22         26         39         35
1          25         20         22         25         39         38
2          20         19         20         21         33         30
3          20         18         20         24         41         35
4          26         21         26         30         41         38
5          18         16         21         25         34         33
6          20         15         19         24         39         35
7          21         23         24         25         35         31
8          24         18         21         28         45         40
9          25         20         24         29         44         39
10         18         16         16         17         31         32
11         23         17         20         26         44         40
12         25         19         25         33         46         38
13         23         18         25         31         43         38
14         20         17         21         21         30         29
15         20         18         21         24         39         33
16         21         19         20         21         31         28
17         20         18         28         26         30         28

[18 rows x 121 columns]>

In [34]:
# '단위' 열과 마지막 열 'Unnamed' 열을 제거
fd_d.drop(columns='단위', inplace=True)
fd_d.head(3)

,구분,항목,2013.01 월,2013.04 월,2013.05 월,2013.06 월,2013.07 월,2013.08 월,2013.09 월,2013.10 월,...,2022.03 월,2022.04 월,2022.05 월,2022.06 월,2022.07 월,2022.08 월,2022.09 월,2022.10 월,2022.11 월,2022.12 월
0,총계,월평균,64.0,54.0,60.0,46.0,38.0,40.0,33.0,36.0,...,42,39,33,22,22,19,22,26,39,35
1,서울,월평균,64.0,52.0,55.0,40.0,34.0,35.0,28.0,29.0,...,41,45,33,22,25,20,22,25,39,38
2,부산,월평균,56.0,49.0,62.0,47.0,47.0,47.0,33.0,38.0,...,38,32,31,19,20,19,20,21,33,30

In [38]:
# melt 함수를 사용하여 데이터 재구성
# '구분' 열을 id_vars로 지정하여 지역 정보를 유지
# 나머지 열들은 연도와 월 정보로 변환됨
df_melted = pd.melt(fd_d, id_vars=['구분'], var_name='날짜', value_name='값', value_vars=fd_d.columns[2:])

# '날짜' 열에서 연도와 월을 분리
df_melted['연도'] = df_melted['날짜'].apply(lambda x: x.split('.')[0])
df_melted['월'] = df_melted['날짜'].apply(lambda x: x.split('.')[1].split()[0])

In [39]:
df_melted

      구분         날짜     값    연도   월
0     총계  2013.01 월  64.0  2013  01
1     서울  2013.01 월  64.0  2013  01
2     부산  2013.01 월  56.0  2013  01
3     대구  2013.01 월  65.0  2013  01
4     인천  2013.01 월  63.0  2013  01
...   ..        ...   ...   ...  ..
2119  전북  2022.12 월    38  2022  12
2120  전남  2022.12 월    29  2022  12
2121  경북  2022.12 월    33  2022  12
2122  경남  2022.12 월    28  2022  12
2123  제주  2022.12 월    28  2022  12

[2124 rows x 5 columns]

In [43]:
# DataFrame을 CSV 파일로 저장하기
df_melted.to_csv('/content/drive/MyDrive/Data/미먼 데이터.csv', index=False, encoding='cp949')

In [47]:
ozon.head()

,Unnamed: 0,주소(시도),일시,평균기온(°C),평균최저기온(°C),평균최고기온(°C),월합강수량(00~24h만)(mm),아황산가스(ppm),이산화질소(ppm),As(μg/m³),...,Cu,Fe,Mn,Ni,Pb,오존(ppm),미세먼지,인구대비 천식,인구대비 비염,인구대비 아토피
0,0,강원,13.Jan,-4.700000,-9.707692,0.838462,39.961538,0.01,0.028,0.008600,...,0.020425,0.960825,0.069225,0.003475,0.093475,0.018,72.0,0.006959,0.037647,0.002588
1,1,강원,13.Feb,-1.484615,-6.792308,3.869231,36.992308,0.007,0.023,0.005675,...,0.018900,1.093250,0.059775,0.003575,0.056675,0.024,NaN,0.006662,0.035763,0.002615
2,2,강원,13.Mar,4.946154,-1.000000,11.315385,54.123077,0.005,0.021,0.010425,...,0.034725,2.283200,0.164425,0.008450,0.100750,0.03,NaN,0.008314,0.043735,0.002685
3,3,강원,13.Apr,8.830769,3.253846,14.584615,62.561538,0.004,0.017,0.002950,...,0.013025,1.181400,0.055450,0.003825,0.037925,0.037,57.0,0.007726,0.040480,0.002679
4,4,강원,13.May,16.892308,11.269231,23.100000,91.561538,0.003,0.015,0.005950,...,0.021325,1.175250,0.158575,0.004225,0.050325,0.041,60.0,0.006778,0.032398,0.003026

In [49]:
from datetime import datetime

# 'Date' 열을 datetime으로 변환하고 연도와 월 추출
ozon['Year'] = ozon['일시'].apply(lambda x: datetime.strptime(x, '%y.%b').year)
ozon['Month'] = ozon['일시'].apply(lambda x: datetime.strptime(x, '%y.%b').month)

ozon.head()

,Unnamed: 0,주소(시도),일시,평균기온(°C),평균최저기온(°C),평균최고기온(°C),월합강수량(00~24h만)(mm),아황산가스(ppm),이산화질소(ppm),As(μg/m³),...,Mn,Ni,Pb,오존(ppm),미세먼지,인구대비 천식,인구대비 비염,인구대비 아토피,Year,Month
0,0,강원,13.Jan,-4.700000,-9.707692,0.838462,39.961538,0.01,0.028,0.008600,...,0.069225,0.003475,0.093475,0.018,72.0,0.006959,0.037647,0.002588,2013,1
1,1,강원,13.Feb,-1.484615,-6.792308,3.869231,36.992308,0.007,0.023,0.005675,...,0.059775,0.003575,0.056675,0.024,NaN,0.006662,0.035763,0.002615,2013,2
2,2,강원,13.Mar,4.946154,-1.000000,11.315385,54.123077,0.005,0.021,0.010425,...,0.164425,0.008450,0.100750,0.03,NaN,0.008314,0.043735,0.002685,2013,3
3,3,강원,13.Apr,8.830769,3.253846,14.584615,62.561538,0.004,0.017,0.002950,...,0.055450,0.003825,0.037925,0.037,57.0,0.007726,0.040480,0.002679,2013,4
4,4,강원,13.May,16.892308,11.269231,23.100000,91.561538,0.003,0.015,0.005950,...,0.158575,0.004225,0.050325,0.041,60.0,0.006778,0.032398,0.003026,2013,5

In [55]:
#df_melted의 'Year', 'Month' 열을 정수형으로 변환
df_melted['Year'] = df_melted['Year'].astype(int)
df_melted['Month'] = df_melted['Month'].astype(int)

In [58]:
# 병합을 위해 df_melted 데이터프레임의 '연도', '월' 열 이름을 'Year', 'Month'로 변경
df_melted.rename(columns={'연도': 'Year', '월': 'Month', '구분' : '주소(시도)'}, inplace=True)

# ozon 데이터프레임과 df_melted 데이터프레임을 'Year'와 'Month' 열을 기준으로 병합
merged_df = pd.merge(ozon, df_melted, on=['Year', 'Month', '주소(시도)'], how='left')

merged_df[merged_df['주소(시도)'] == '제주']

,Unnamed: 0,주소(시도),일시,평균기온(°C),평균최저기온(°C),평균최고기온(°C),월합강수량(00~24h만)(mm),아황산가스(ppm),이산화질소(ppm),As(μg/m³),...,Pb,오존(ppm),미세먼지,인구대비 천식,인구대비 비염,인구대비 아토피,Year,Month,날짜,값
1596,1596,제주,13.Jan,5.700,2.725,8.700,29.525,0.004,0.013,NaN,...,NaN,0.031,NaN,0.006828,0.050527,0.003861,2013,1,2013.01 월,42.0
1597,1597,제주,13.Feb,6.550,3.225,9.800,84.050,0.003,0.013,NaN,...,NaN,0.031,NaN,0.007182,0.056055,0.003542,2013,2,NaN,NaN
1598,1598,제주,13.Mar,10.250,5.925,14.850,58.475,0.003,0.012,NaN,...,NaN,0.037,NaN,0.008587,0.056550,0.003851,2013,3,NaN,NaN
1599,1599,제주,13.Apr,13.250,9.325,17.250,100.825,0.002,0.010,NaN,...,NaN,0.042,NaN,0.007954,0.048887,0.003944,2013,4,2013.04 월,42.0
1600,1600,제주,13.May,18.250,14.900,22.000,117.500,0.003,0.011,NaN,...,NaN,0.043,NaN,0.006714,0.038355,0.004332,2013,5,2013.05 월,53.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1711,1711,제주,22.Aug,28.100,25.625,31.100,191.100,0.001,0.005,NaN,...,NaN,0.032,NaN,0.002580,0.032314,0.003306,2022,8,2022.08 월,18
1712,1712,제주,22.Sep,23.975,21.650,26.900,306.275,0.001,0.006,NaN,...,NaN,0.04,NaN,0.003623,0.032708,0.002927,2022,9,2022.09 월,28
1713,1713,제주,22.Oct,18.325,15.425,21.525,19.625,0.001,0.006,NaN,...,NaN,0.042,NaN,0.004255,0.047224,0.002804,2022,10,2022.10 월,26
1714,1714,제주,22.Nov,15.475,12.100,19.275,102.475,0.001,0.008,NaN,...,NaN,0.042,NaN,0.003258,0.040077,0.002655,2022,11,2022.11 월,30
1715,1715,제주,22.Dec,6.800,4.025,9.750,34.325,0.001,0.007,NaN,...,NaN,0.037,NaN,0.003375,0.048915,0.002622,2022,12,2022.12 월,28

In [59]:
# 병합된 데이터프레임(예를 들어 merged_df라고 가정)에서 열을 제거
merged_df = merged_df.drop(['Year', 'Month', '날짜', '미세먼지'], axis=1)

# 결과 확인
merged_df.head()

,Unnamed: 0,주소(시도),일시,평균기온(°C),평균최저기온(°C),평균최고기온(°C),월합강수량(00~24h만)(mm),아황산가스(ppm),이산화질소(ppm),As(μg/m³),...,Cu,Fe,Mn,Ni,Pb,오존(ppm),인구대비 천식,인구대비 비염,인구대비 아토피,값
0,0,강원,13.Jan,-4.700000,-9.707692,0.838462,39.961538,0.01,0.028,0.008600,...,0.020425,0.960825,0.069225,0.003475,0.093475,0.018,0.006959,0.037647,0.002588,72.0
1,1,강원,13.Feb,-1.484615,-6.792308,3.869231,36.992308,0.007,0.023,0.005675,...,0.018900,1.093250,0.059775,0.003575,0.056675,0.024,0.006662,0.035763,0.002615,NaN
2,2,강원,13.Mar,4.946154,-1.000000,11.315385,54.123077,0.005,0.021,0.010425,...,0.034725,2.283200,0.164425,0.008450,0.100750,0.03,0.008314,0.043735,0.002685,NaN
3,3,강원,13.Apr,8.830769,3.253846,14.584615,62.561538,0.004,0.017,0.002950,...,0.013025,1.181400,0.055450,0.003825,0.037925,0.037,0.007726,0.040480,0.002679,57.0
4,4,강원,13.May,16.892308,11.269231,23.100000,91.561538,0.003,0.015,0.005950,...,0.021325,1.175250,0.158575,0.004225,0.050325,0.041,0.006778,0.032398,0.003026,60.0

In [60]:
# DataFrame을 CSV 파일로 저장하기
merged_df.to_csv('/content/drive/MyDrive/Data/최종 미먼 data.csv', index=False, encoding='cp949')